spring:
  profiles:
    active: local
    include: oauth

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

jwt:
  issuer: local@engtalkmo.com
  secret_key: engtalkmo-secret-key-1dsadasdsdajio1sad!!3#