spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/engtalkmo
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  sql:
    init.mode: always

  jpa:
    open-in-view: false
    hibernate.ddl-auto: create-drop
    properties.hibernate:
      format_sql: true # 쿼리 출력
      default_batch_fetch_size: 100
    defer-datasource-initialization: true # 테이블 생성 후 data.sql 실행

logging.level:
  org.hibernate.SQL: debug
